### ISSUE TITLE
LED Part Number

### ISSUE THREAD

**Issue by Chirishman** [LastContinue/ctrl-info#2]
Hey, the red sub-led in my LED #95 is dead. Any idea what the part number would be to order the LEDs?

**Comment by LastContinue** [comment]
Sorry, I apparently don't have this repo setup to notify me when issues come in 🙇‍♂️

I do not know about this right off the top of my head, but I can definitely look into this for you and at least give you a vague idea of "try to get something like this"

**Comment by LastContinue** [comment]
Quick update on this: I haven't been able to find the exact type of LED to replace this. The little tabs that allow you to mount it above or below (via a hole) the board seem to be unusual (but there's no way these are custom made). 

It _looks_ like what's apparently called a `1210 3528` but again, the tabs are off. 

Here's a picture
![img_20181026_075516](https://user-images.githubusercontent.com/20746446/47609904-adcb1e00-da0d-11e8-803f-2dff62b2c23d.jpg)

Have you tried putting voltage across all of the pins? There is a chance that your "R" just isn't soldered correctly.

I'll keep looking. I asked some component savvy friends about it and I'm waiting to hear back.

**Comment by LastContinue** [comment]
GOT IT!!! One of my friends came through and found this:

https://www.aliexpress.com/item/70pcs-SMD-3528-6028-RGB-LED-Common-Anode-SMT-Chip-Tricolor-Red-Green-Blue-1210-Shine/32834931333.html

Gonna let this soak a few days then mark it "closed".  Good luck!!!

**Comment by Chirishman** [comment]
Thank you! I did put voltage across the pins and red doesn't light up on that specific LED.

Thanks for the find! I'm ordering those now!

**Comment by LastContinue** [comment]
@Chirishman let me know when you get these in and if they work out! I'm really curious. I'm going to close this issue just for housekeeping's sake.

**Comment by Chirishman** [comment]
Almost. So close. It's the right package and the right pinout but it's **super** dim. As in barely visible that it's on when directly looking at the package.

**Comment by LastContinue** [comment]
That's really unfortunate! I wonder if there's a same package, but higher wattage? (Probably, but my patience for scouring Ali Express is pretty limited)

Well thanks for reporting back.
