### ISSUE TITLE
Which chip provided the USB passthough feature ?

### ISSUE THREAD

**Issue by 203Null** [LastContinue/ctrl-info#3]
I want to add this into my own keyboard design but I can't find any IC that provides such a feature. I don't personally have a Ctrl, so I can just take it apart and tell which chip is used. Can you find the chip that Ctrl used or can you sent me a list of chip with their label that is on the PCB? Thank you.

**Comment by LastContinue** [comment]
Sorry, just now seeing this March 4th (I thought I had this repo set to notify me when an issue is posted).

I know very little about the actual PCB of this board, but I could take a bunch of photos of my spare I bought. Would that be helpful? 

Also, by "pass through" to you mean "ability to plug other USB peripheral into the keyboard and it act like a hub" ?  (mouse, memory card, etc) 

If so "you can't do that with this board"

**Comment by 203Null** [comment]
Then I must overlooked it. Nonetheless, thank you for the reply.
